name: CI For Media-Video-Player-App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    # Step 1: Checkout code
    - uses: actions/checkout@v4

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the application
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Step 5: Run tests (if applicable)
    - name: Test
      run: dotnet test --no-build --verbosity normal
